services:
  - type: web
    name: livelib-backend
    env: docker
    rootDir: .
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
